### ISSUE TITLE
Slow connection to Azure provider

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-azure#188]
Investigate why connecting to the Azure provider is 3x slower than connecting to the Amazon provider.

**Comment by djberg96** [comment]
I don't know how the AWS provider connects, but I suspect part of the issue is the two-part authentication that happens initially for Azure. We make two requests before we can even attempt to collect inventory.

Using rest-client probably doesn't help either, but switching the backend code in azure-armrest is proving difficult.

**Comment by djberg96** [comment]
I don't think there's anything we can do about this because of rest-client. Closing for now.
